site_name: Nautilus Documentation
site_description: Documentation for Nautilus MVP
repo_url: https://github.com/ntls-io/trusted-compute-MVP
site_url: https://ntls-io.github.io/trusted-compute-MVP/
repo_name: ntls-io/trusted-compute-MVP

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/images/logo.png
  favicon: assets/images/logo.ico
  features:
    - navigation.sections
    - navigation.top
    - navigation.footer
    - navigation.expand
    - navigation.indexes
    - navigation.instant 
    - navigation.preload
    - toc.follow
    - toc.integrate
    - search.highlight
    - search.share
    - search.suggest
    - content.tabs.link
    - content.code.copy
    - toc.sticky
    - navigation.breadcrumbs
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css
  - stylesheets/fonts.css

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
  - attr_list
  - md_in_html

# Correct extra section structure
extra:
  generator: false
  links:
    - footer:
      - title: Privacy Policy
        link: /privacy/
      - title: Terms of Service
        link: /terms/

copyright: Copyright &copy; 2024 Nautilus - All rights reserved
  
nav:
  - Home: index.md
  - Installation:
    - SGX MVP Installation Guide: installation/sgx-mvp.md
    - Docker Deployment: installation/docker-deployment.md
  - API Documentation:
    - Overview: api/overview.md
    - Endpoints:
      - Health Check: api/endpoints/health.md
      - Data Pool: api/endpoints/data-pool.md
      - Python Execution: api/endpoints/python-execution.md
      - WASM Execution: api/endpoints/wasm-execution.md
    - Postman Guide: api/postman-collection/usage-guide.md
  - Attestation:
    - Guide: attestation/guide.md
    - Client Setup: attestation/client-setup.md
  - Legal:
    - Privacy Policy: privacy.md
    - Terms of Service: terms.md