[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
drt_manager = "CiHJcJofM1k3iEKh7sHtzWY71HJhzP2rqw6Z6i9h9dwP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./test-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
