[package]
name = "sgx-mvp"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmi = { version = "0.11.0", default-features = false }
wasm-test = { path = "wasm-test" }
serde_json = "1.0.127"

[dev-dependencies]
wabt = "0.10.0"