[package]
name = "sgx-mvp"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmi = { version = "0.11.0", default-features = false }
wasmi-impl = { path = "wasmi-impl" }

[dev-dependencies]
wabt = "0.10.0"