// Nautilus Trusted Compute
// Copyright (C) 2025 Nautilus
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

extern crate github_download;
extern crate json_append;
extern crate python_rust_impl;
extern crate wasmi_impl;

use actix_web::{web, App, HttpResponse, HttpServer, Responder};
use aes_gcm::aead::Aead;
use aes_gcm::{Aes128Gcm, KeyInit, Nonce};
use anyhow::{anyhow, Result};
use github_download::{verify_and_download_python_github, verify_and_download_wasm};
use hkdf::Hkdf;
use json_append::append_json;
use once_cell::sync::Lazy;
use oracle_verify::authz::{authorize, validate_locally, EnclaveConfig};
use oracle_verify::claim::{self, Action};
use oracle_verify::error::ApiError;
use oracle_verify::oracle_client::{HttpOracleTransport, OracleAssertion};
use oracle_verify::state::{
    self, load_identity, replay_key, store_identity, EntryStatus, PoolIdentity, ReplayLedger,
};
use python_rust_impl::run_python;
use rand::RngCore;
use rustls::pki_types::CertificateDer;
use rustls::server::ServerConfig;
use serde::Deserialize;
use serde_json::Value;
use sha2::Sha256;
use std::collections::BTreeMap;
use std::fs::{read, File};
use std::io::{BufReader, Write};
use std::path::Path;
use wasmi_impl::wasm_execution;

/// Serializes all replay-ledger and sealed-state transitions so a
/// redemption can never be consumed twice by concurrent requests.
static STATE_LOCK: Lazy<tokio::sync::Mutex<()>> = Lazy::new(|| tokio::sync::Mutex::new(()));

/// Loads certificates from a PEM file generated by gramine-ratls
fn load_ratls_certificates(cert_path: &str) -> Result<Vec<CertificateDer<'static>>> {
    println!("[+] Loading RA-TLS certificate from: {}", cert_path);

    // Read the entire file content
    let cert_content = std::fs::read_to_string(cert_path)
        .map_err(|e| anyhow!("Failed to read certificate file: {}", e))?;

    // Clean up the certificate content
    let cleaned_cert = cert_content
        .replace(
            "-----BEGIN TRUSTED CERTIFICATE-----",
            "-----BEGIN CERTIFICATE-----",
        )
        .replace(
            "-----END TRUSTED CERTIFICATE-----",
            "-----END CERTIFICATE-----",
        );

    // Create a buffered reader from the cleaned content
    let mut reader = BufReader::new(cleaned_cert.as_bytes());

    // Parse all certificates in the buffer
    let certs: Vec<_> = rustls_pemfile::certs(&mut reader)
        .filter_map(|result| match result {
            Ok(cert) => {
                println!("[+] Successfully parsed certificate");
                Some(cert)
            }
            Err(e) => {
                eprintln!("[!] Error parsing certificate: {}", e);
                None
            }
        })
        .collect();

    if certs.is_empty() {
        return Err(anyhow!("No valid certificates found in {}", cert_path));
    }

    println!("[+] Loaded {} certificate(s)", certs.len());
    Ok(certs)
}

/// Loads private key from a PEM file generated by gramine-ratls
fn load_ratls_private_key(key_path: &str) -> Result<rustls::pki_types::PrivateKeyDer<'static>> {
    println!("[+] Loading RA-TLS private key from: {}", key_path);

    // Open the key file
    let key_file =
        File::open(key_path).map_err(|e| anyhow!("Failed to open private key file: {}", e))?;
    let mut reader = BufReader::new(key_file);

    // Parse as an EC private key
    if let Some(key) = rustls_pemfile::ec_private_keys(&mut reader)
        .next()
        .transpose()
        .map_err(|e| anyhow!("Failed to parse EC private key: {}", e))?
    {
        println!("[+] Found EC private key");
        return Ok(rustls::pki_types::PrivateKeyDer::Sec1(key));
    }

    Err(anyhow!("No valid EC private key found in {}", key_path))
}

/// Reads and validates a PEM file with improved error handling
fn read_pem_file(path: &str) -> Result<String> {
    let content = std::fs::read_to_string(path)
        .map_err(|e| anyhow!("Failed to read PEM file {}: {}", path, e))?;

    // Validate PEM structure
    if !content.contains("-----BEGIN") || !content.contains("-----END") {
        return Err(anyhow!("Invalid PEM format in file: {}", path));
    }

    Ok(content)
}

/// Verifies that the PEM files exist and contain valid PEM data
pub fn verify_ratls_files(cert_path: &str, key_path: &str) -> Result<()> {
    println!("[+] Verifying RA-TLS PEM files");

    // Check if files exist
    if !Path::new(cert_path).exists() {
        return Err(anyhow!("Certificate file missing: {}", cert_path));
    }
    if !Path::new(key_path).exists() {
        return Err(anyhow!("Private key file missing: {}", key_path));
    }

    // Validate PEM format with detailed error reporting
    if let Err(e) = read_pem_file(cert_path) {
        eprintln!("[!] Certificate validation failed:");
        eprintln!("[!] Error: {}", e);
        eprintln!("[!] File path: {}", cert_path);
        return Err(anyhow!("Certificate validation failed: {}", e));
    }

    if let Err(e) = read_pem_file(key_path) {
        eprintln!("[!] Private key validation failed:");
        eprintln!("[!] Error: {}", e);
        eprintln!("[!] File path: {}", key_path);
        return Err(anyhow!("Private key validation failed: {}", e));
    }

    println!("[+] RA-TLS PEM files verified successfully");
    Ok(())
}

/// Selects the rustls crypto provider for the whole process.
///
/// rustls 0.23 refuses to guess when more than one provider is compiled in, and
/// both are: cargo feature unification enables `ring` (via actix-tls) *and*
/// `aws-lc-rs` (via reqwest/hyper-rustls). Without this, the enclave starts,
/// generates its RA-TLS certificate, and only then panics inside
/// `ServerConfig::builder()` with "Could not automatically determine the
/// process-level CryptoProvider" — leaving a container that looks healthy to
/// `docker ps` but never listens, and an attestation preflight that fails with
/// nothing but a connection error to go on.
///
/// Pinning it here also makes the choice reviewable rather than an accident of
/// dependency resolution: this provider is inside the enclave's TCB and is
/// measured into MRENCLAVE, so it must not be able to change silently when a
/// transitive dependency flips a feature.
///
/// `ring` is chosen over `aws-lc-rs` for its longer track record under Gramine;
/// `aws-lc-sys` also needs a C toolchain workaround in the enclave image
/// (see `docker/Dockerfile`'s `CC=clang`, for GCC bug 95189).
fn install_crypto_provider() -> Result<()> {
    // Err means a provider is already installed, which is fine and idempotent —
    // it only matters that exactly one is active before any TLS is configured.
    if rustls::crypto::ring::default_provider()
        .install_default()
        .is_err()
    {
        let installed = rustls::crypto::CryptoProvider::get_default()
            .ok_or_else(|| anyhow!("rustls reported a provider was installed, but none is set"))?;
        println!(
            "[+] rustls crypto provider already installed ({} cipher suites)",
            installed.cipher_suites.len()
        );
        return Ok(());
    }

    println!("[+] rustls crypto provider installed: ring");
    Ok(())
}

/// Configures TLS with Gramine RA-TLS certificates
pub fn configure_ratls(cert_path: &str, key_path: &str) -> Result<ServerConfig> {
    // Must precede ServerConfig::builder(), which panics without a provider.
    install_crypto_provider()?;

    // First verify the PEM files
    verify_ratls_files(cert_path, key_path)?;

    // Load certificates and private key
    let certs = load_ratls_certificates(cert_path)?;
    let key = load_ratls_private_key(key_path)?;

    // Create server config
    let config = ServerConfig::builder()
        .with_no_client_auth()
        .with_single_cert(certs, key)
        .map_err(|e| anyhow!("Failed to create TLS config: {}", e))?;

    println!("[+] Successfully configured RA-TLS with PEM files");
    Ok(config)
}

// Define a health check route
async fn health_check() -> impl Responder {
    HttpResponse::Ok()
        .append_header(("Content-Type", "text/plain"))
        .body("Server is running")
}

/// Derives a new key using HKDF with a given base key, salt, and purpose.
fn derive_key(base_key: &[u8], salt: &[u8]) -> Result<[u8; 16]> {
    let hkdf = Hkdf::<Sha256>::new(Some(salt), base_key);
    let mut derived_key = [0u8; 16];
    hkdf.expand(b"sealing", &mut derived_key)
        .map_err(|e| anyhow!("Key derivation failed: {}", e))?;
    Ok(derived_key)
}

/// Generates a 16-byte random salt.
fn generate_salt() -> [u8; 16] {
    let mut salt = [0u8; 16];
    rand::rngs::OsRng.fill_bytes(&mut salt);
    salt
}

/// Reads the attestation key and derives the encryption key using a salt.
fn read_and_derive_key(salt: &[u8]) -> Result<[u8; 16]> {
    let base_key = read("/dev/attestation/keys/_sgx_mrenclave")
        .map_err(|e| anyhow!("Failed to read key: {}", e))?;
    if base_key.len() != 16 {
        return Err(anyhow!(
            "Invalid key length: expected 16 bytes, got {}",
            base_key.len()
        ));
    }
    derive_key(&base_key, salt)
}

/// Encrypts and seals the data.
fn seal_data(data: &Value, salt: Option<&[u8]>) -> Result<Vec<u8>> {
    // Generate or use the provided salt
    let salt = match salt {
        Some(existing_salt) => existing_salt.to_vec(),
        None => generate_salt().to_vec(),
    };

    // Derive the encryption key
    let derived_key = read_and_derive_key(&salt)?;
    let cipher = Aes128Gcm::new_from_slice(&derived_key)
        .map_err(|e| anyhow!("Failed to initialize AES-GCM: {}", e))?;

    // Generate a secure nonce (12 bytes as required by AES-GCM)
    let mut nonce_bytes = [0u8; 12];
    rand::rngs::OsRng.fill_bytes(&mut nonce_bytes);
    let nonce = Nonce::from_slice(&nonce_bytes);

    // Serialize the data to JSON
    let serialized_data =
        serde_json::to_vec(data).map_err(|e| anyhow!("Failed to serialize JSON: {}", e))?;

    // Encrypt the serialized data
    let ciphertext = cipher
        .encrypt(nonce, serialized_data.as_ref())
        .map_err(|e| anyhow!("Encryption failed: {}", e))?;

    // Combine salt, nonce, and ciphertext into a single Vec<u8>
    let mut sealed_data = Vec::with_capacity(salt.len() + nonce_bytes.len() + ciphertext.len());
    sealed_data.extend_from_slice(&salt);
    sealed_data.extend_from_slice(&nonce_bytes);
    sealed_data.extend_from_slice(&ciphertext);

    Ok(sealed_data)
}

/// Saves data to a file.
fn save_to_file(data: &[u8]) -> Result<()> {
    let path = state::data_dir().join("data_pool");
    let mut file = File::create(path).map_err(|e| anyhow!("Failed to create file: {}", e))?;
    file.write_all(data)
        .map_err(|e| anyhow!("Failed to write to file: {}", e))?;
    Ok(())
}

// TODO Update threading
#[tokio::main(flavor = "current_thread")]
async fn main() -> Result<()> {
    println!("[+] Enclave created successfully, starting server...");

    // Before anything touches TLS — the oracle client uses rustls too, so this
    // must not be left to whichever code path happens to run first.
    install_crypto_provider()?;

    // Path to certificate and key files
    let certs_file_path = "/tmp/tlscert.pem";
    let key_file_path = "/tmp/tlskey.pem";

    // Load RA-TLS configuration
    let tls_config = configure_ratls(certs_file_path, key_file_path)?;

    // Oracle trust anchors come from the measured manifest; warn early if
    // missing so protected endpoints failing with `enclave_unconfigured`
    // is no surprise.
    match EnclaveConfig::from_env() {
        Ok(config) => println!(
            "[+] Oracle verification enabled: url={} cluster={} program={}",
            config.oracle_url, config.cluster, config.program
        ),
        Err(e) => eprintln!("[!] Oracle verification NOT configured: {}", e),
    }

    // Start the Actix Web server
    HttpServer::new(|| {
        App::new()
            .route("/health", web::get().to(health_check)) // Health check route
            .route("/execute_python", web::post().to(execute_python_handler)) // Python execution route
            .route("/execute_wasm", web::post().to(execute_wasm_handler)) // WASM execution route
            .route(
                "/create_data_pool",
                web::post().to(create_data_pool_handler),
            ) // Create new data pool
            .route("/view_data", web::get().to(view_data_handler)) // DEBUG ONLY — marked for removal
            .route("/append_data", web::post().to(append_data_handler)) // Append data into data pool
    })
    .bind_rustls_0_23("127.0.0.1:8080", tls_config)?
    .run()
    .await
    .map_err(|e| anyhow!("Actix web server error: {}", e))
}

/// Protected request envelope: a wallet-signed claim, its signature, and
/// (for init/append) the exact payload string the claim's payload_sha256
/// commits to. Runtime, GitHub URL, and code hash are NOT accepted from the
/// client; they come from the verified oracle assertion cross-checked
/// against the wallet-signed claim.
#[derive(Deserialize)]
struct ProtectedRequest {
    claim: BTreeMap<String, String>,
    wallet_signature: String,
    /// JSON document as a string; hashed byte-for-byte. Absent for execute.
    payload: Option<String>,
}

struct VerifiedOp {
    claim: claim::ClaimContext,
    assertion: OracleAssertion,
    replay_key: String,
}

enum PreCheck {
    Cached(Value),
    Fresh,
}

/// Local claim checks plus a cached-retry probe, before the oracle is asked.
/// A redemption is never consumed when oracle verification fails, and an
/// identical successful retry is served from the sealed result cache.
async fn pre_check(claim: &claim::ClaimContext) -> Result<(PreCheck, String), ApiError> {
    let key = replay_key(claim.get("cluster"), claim.get("program"), claim.get("tx"));
    let _guard = STATE_LOCK.lock().await;
    let ledger = ReplayLedger::load()?;
    if let Some(entry) = ledger.get(&key) {
        return match entry.status {
            EntryStatus::Succeeded if entry.claim_digest == claim.digest_hex() => Ok((
                PreCheck::Cached(entry.result.clone().unwrap_or(Value::Null)),
                key,
            )),
            EntryStatus::Succeeded => Err(ApiError::replay(
                "redemption already consumed with a different claim",
            )),
            EntryStatus::Reserved => Err(ApiError::replay("redemption is already in progress")),
            EntryStatus::Failed => Err(ApiError::replay(
                "redemption was consumed by a failed execution (DRT already burned)",
            )),
        };
    }
    Ok((PreCheck::Fresh, key))
}

/// Verify claim + oracle assertion and atomically reserve the redemption.
async fn verify_and_reserve(
    action: Action,
    body: &ProtectedRequest,
    payload: &str,
) -> Result<Result<VerifiedOp, Value>, ApiError> {
    let config = EnclaveConfig::from_env()?;
    let claim = validate_locally(
        action,
        body.claim.clone(),
        &body.wallet_signature,
        payload,
        &config,
    )?;

    // Pool binding: one enclave, one pool.
    let identity = load_identity()?;
    match (action, &identity) {
        (Action::PoolInitialize, Some(_)) => {
            return Err(ApiError::pool_binding("pool is already initialized"));
        }
        (Action::PoolInitialize, None) => {}
        (_, None) => {
            return Err(ApiError::pool_binding("pool is not initialized"));
        }
        (_, Some(identity)) => {
            if claim.get("pool") != identity.pool
                || claim.get("cluster") != identity.cluster
                || claim.get("program") != identity.program
            {
                return Err(ApiError::pool_binding(
                    "claim is not for the pool bound to this enclave",
                ));
            }
        }
    }

    let (pre, key) = pre_check(&claim).await?;
    if let PreCheck::Cached(result) = pre {
        return Ok(Err(result));
    }

    // Oracle round-trip happens before the redemption is reserved, so an
    // oracle failure never consumes it.
    let transport = HttpOracleTransport {
        base_url: config.oracle_url.clone(),
        timeout: config.oracle_timeout,
    };
    let assertion = authorize(&claim, &body.wallet_signature, &transport, &config)?;

    {
        let _guard = STATE_LOCK.lock().await;
        let mut ledger = ReplayLedger::load()?;
        ledger.reserve(&key, &claim.digest_hex())?;
    }
    Ok(Ok(VerifiedOp {
        claim,
        assertion,
        replay_key: key,
    }))
}

async fn record_success(key: &str, result: Option<Value>) -> Result<(), ApiError> {
    let _guard = STATE_LOCK.lock().await;
    ReplayLedger::load()?.record_success(key, result)
}

async fn record_failure(key: &str) {
    let _guard = STATE_LOCK.lock().await;
    if let Ok(mut ledger) = ReplayLedger::load() {
        let _ = ledger.record_failure(key);
    }
}

const POOL_CREATED_MSG: &str = "Data pool created, sealed, and saved successfully";
const DATA_APPENDED_MSG: &str = "Data appended, sealed, and saved successfully";

/// Handler for the `create_data_pool` API. One-time pool initialization:
/// verifies the PoolCreated claim, seals the seed data, and binds this
/// enclave to the pool PDA.
async fn create_data_pool_handler(
    body: web::Json<ProtectedRequest>,
) -> Result<HttpResponse, ApiError> {
    let payload = body
        .payload
        .as_deref()
        .ok_or_else(|| ApiError::invalid_claim("payload is required"))?;
    let op = match verify_and_reserve(Action::PoolInitialize, &body, payload).await? {
        Ok(op) => op,
        Err(cached) => return Ok(HttpResponse::Ok().json(cached)),
    };

    let parsed: Value = serde_json::from_str(payload)
        .map_err(|e| ApiError::invalid_claim(format!("payload is not valid JSON: {e}")))?;
    let schema = parsed.get("schema").cloned();
    let data = parsed.get("data").cloned();
    let (Some(schema), Some(data)) = (schema, data) else {
        record_failure(&op.replay_key).await;
        return Err(ApiError::invalid_claim(
            "payload must contain `schema` and `data`",
        ));
    };

    let result = seal_data(&data, None)
        .and_then(|sealed| save_to_file(&sealed))
        .map_err(|e| ApiError::internal(format!("failed to seal pool data: {e}")));
    if let Err(err) = result {
        record_failure(&op.replay_key).await;
        return Err(err);
    }

    store_identity(&PoolIdentity {
        pool: op.claim.get("pool").to_string(),
        owner: op.claim.get("claimant").to_string(),
        cluster: op.claim.get("cluster").to_string(),
        program: op.claim.get("program").to_string(),
        init_tx: op.claim.get("tx").to_string(),
        schema,
    })?;
    record_success(&op.replay_key, Some(Value::String(POOL_CREATED_MSG.into()))).await?;
    Ok(HttpResponse::Ok().json(Value::String(POOL_CREATED_MSG.into())))
}

/// Handler for the `append_data` API: verified AppendDRT redemption plus
/// the exact JSON payload the wallet-signed claim committed to.
async fn append_data_handler(body: web::Json<ProtectedRequest>) -> Result<HttpResponse, ApiError> {
    let payload = body
        .payload
        .as_deref()
        .ok_or_else(|| ApiError::invalid_claim("payload is required"))?;
    let op = match verify_and_reserve(Action::Append, &body, payload).await? {
        Ok(op) => op,
        Err(cached) => return Ok(HttpResponse::Ok().json(cached)),
    };

    let new_data: Value = serde_json::from_str(payload)
        .map_err(|e| ApiError::invalid_claim(format!("payload is not valid JSON: {e}")))?;

    let result = unseal_data()
        .and_then(|existing| append_json(&existing, &new_data))
        .and_then(|updated| seal_data(&updated, None))
        .and_then(|sealed| save_to_file(&sealed));
    match result {
        Ok(()) => {
            record_success(
                &op.replay_key,
                Some(Value::String(DATA_APPENDED_MSG.into())),
            )
            .await?;
            Ok(HttpResponse::Ok().json(Value::String(DATA_APPENDED_MSG.into())))
        }
        Err(e) => {
            // The DRT was burned on-chain; the redemption stays consumed.
            record_failure(&op.replay_key).await;
            Err(ApiError::new(
                500,
                "execution_failed",
                format!("append failed after redemption was consumed: {e}"),
            ))
        }
    }
}

/// Shared execute path: runtime, GitHub URL, and expected code hash come
/// exclusively from the verified oracle assertion (cross-checked against
/// the wallet-signed claim); the WASM schema comes from sealed state.
async fn handle_execute(
    action: Action,
    body: web::Json<ProtectedRequest>,
) -> Result<HttpResponse, ApiError> {
    if body.payload.is_some() {
        return Err(ApiError::invalid_claim("execute requests carry no payload"));
    }
    let op = match verify_and_reserve(action, &body, "").await? {
        Ok(op) => op,
        Err(cached) => return Ok(HttpResponse::Ok().json(cached)),
    };
    let github_url = op.assertion.github_url.clone().unwrap_or_default();
    let code_hash = op.assertion.code_hash.clone().unwrap_or_default();

    let execution = unseal_data()
        .map_err(|e| anyhow!("failed to unseal data: {e}"))
        .and_then(|json_data| match action {
            Action::ExecuteWasm => {
                let schema = load_identity()
                    .ok()
                    .flatten()
                    .map(|identity| identity.schema)
                    .ok_or_else(|| anyhow!("pool schema unavailable"))?;
                execute_wasm_binary(&github_url, &code_hash, &json_data, &schema)
            }
            Action::ExecutePython => execute_python_script(&github_url, &code_hash, &json_data),
            _ => Err(anyhow!("unsupported execute action")),
        });

    match execution {
        Ok(result) => {
            record_success(&op.replay_key, Some(result.clone())).await?;
            Ok(HttpResponse::Ok().json(result))
        }
        Err(e) => {
            eprintln!("[!] Execution error: {}", e);
            // The DRT was burned on-chain; the redemption stays consumed.
            record_failure(&op.replay_key).await;
            Err(ApiError::new(
                500,
                "execution_failed",
                format!("execution failed after redemption was consumed: {e}"),
            ))
        }
    }
}

/// Handler for the `execute_wasm` API
async fn execute_wasm_handler(body: web::Json<ProtectedRequest>) -> Result<HttpResponse, ApiError> {
    handle_execute(Action::ExecuteWasm, body).await
}

fn execute_wasm_binary(
    github_url: &str,
    expected_hash: &str,
    input_data: &Value,
    input_schema: &Value,
) -> Result<Value> {
    // Temporary path to save the downloaded WASM binary
    let wasm_path = "/tmp/downloaded_wasm.wasm";

    // Step 1: Download and verify the WASM binary
    verify_and_download_wasm(&github_url, wasm_path, expected_hash)
        .map_err(|e| anyhow!("Failed to download or verify WASM binary: {}", e))?;

    // Step 2: Execute the WASM binary with the data and schema
    let result = match wasm_execution(wasm_path, input_data.clone(), input_schema.clone()) {
        Ok(res) => res,
        Err(e) => {
            eprintln!("[!] WASM execution error: {}", e);
            return Err(anyhow!("WASM execution failed with error: {}", e));
        }
    };

    // Step 3: Delete the temporary file
    if let Err(e) = std::fs::remove_file(wasm_path) {
        eprintln!(
            "[!] Warning: Failed to delete temporary file {}: {}",
            wasm_path, e
        );
    }

    // Step 4: Log and return the result
    println!(
        "[+] WASM Execution Result: {}",
        serde_json::to_string_pretty(&result)?
    );
    Ok(result)
}

/// HTTP POST handler to execute a Python script authorized by a verified
/// DRT redemption (code identity from the oracle assertion, never the client)
async fn execute_python_handler(
    body: web::Json<ProtectedRequest>,
) -> Result<HttpResponse, ApiError> {
    handle_execute(Action::ExecutePython, body).await
}

fn execute_python_script(
    github_url: &str,
    expected_hash: &str,
    input_data: &Value,
) -> Result<Value> {
    // Temporary path to save the downloaded Python script
    let script_path = "/tmp/downloaded_script.py";

    // Step 1: Download and verify the script
    verify_and_download_python_github(&github_url, script_path, expected_hash)
        .map_err(|e| anyhow!("Failed to download or verify script: {}", e))?;

    // Step 2: Execute the Python script
    let result = run_python(input_data, script_path)
        .map_err(|e| anyhow!("Python execution error: {}", e))?;

    // Step 3: Delete the temporary file
    if let Err(e) = std::fs::remove_file(script_path) {
        eprintln!(
            "[!] Warning: Failed to delete temporary file {}: {}",
            script_path, e
        );
    }

    // Step 4: Format script output
    // Debug print the result, remove in production
    println!(
        "[+] Python Script Result: {}",
        serde_json::to_string_pretty(&result)?
    );

    Ok(result)
}

/// Decrypts and unseals the data.
fn unseal_data() -> Result<Value> {
    let sealed_data = std::fs::read(state::data_dir().join("data_pool"))
        .map_err(|e| anyhow!("Failed to read sealed data: {}", e))?;
    if sealed_data.len() < 28 {
        return Err(anyhow!(
            "Invalid sealed data: insufficient length for salt, nonce, and ciphertext"
        ));
    }
    let (salt, remaining) = sealed_data.split_at(16);
    let (nonce, ciphertext) = remaining.split_at(12);

    let derived_key = read_and_derive_key(salt)?;
    let cipher = Aes128Gcm::new_from_slice(&derived_key)
        .map_err(|e| anyhow!("Failed to initialize AES-GCM: {}", e))?;
    let plaintext = cipher
        .decrypt(Nonce::from_slice(nonce), ciphertext)
        .map_err(|e| anyhow!("Decryption failed: {}", e))?;
    serde_json::from_slice(&plaintext).map_err(|e| anyhow!("Failed to parse JSON: {}", e))
}

/// Handler for the `view_data` API
///
/// DEBUG/TESTING ONLY — returns the fully unsealed pool with no
/// authorization. Kept while this is a research prototype so behaviour can
/// be inspected end-to-end; MARKED FOR REMOVAL and must never ship in any
/// production deployment (it bypasses the "raw data never leaves the
/// enclave" guarantee).
async fn view_data_handler() -> impl Responder {
    // Unseal (decrypt) the data
    match unseal_data() {
        Ok(json_data) => HttpResponse::Ok().json(json_data), // Return the JSON data
        Err(e) => {
            eprintln!("[!] Error unsealing data: {}", e);
            HttpResponse::InternalServerError().body("Failed to unseal data")
        }
    }
}
